<?php

/**
 * @file
 *  XassidaReader Drupal Module Main File
 *
 * @author
 *  Papa Pathe SENE
 *  pathe.sene@xarala.sn
 *  pathe.sene@gmail.com
 * 
 * @copyright
 * 	Xarala Web Studios
 * 
 */

/**
 * ************************************************************************************
 *
 * Implements hook_menu()
 *
 * @return Array
 * @author Papa Pathe SENE
 * 
 * ************************************************************************************
 */
function xassidareader_menu() {

/**
 * A menu item to configure XassidaReader
 * ------------------------------------------------------------------------
 */
  $items['admin/config/content/xassidareader'] = array(
    'title' => 'XassidaReader',
    'description' => 'Configure how xassidareader works in your setup ',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('xassidareader_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'xassidareader.admin.inc',
  );

 /**
  * A menu to list the xassaides 
  * ------------------------------------------------------------------------
  */
 $items['xassidareader'] = array(
 	'title' => 'XassidaReader',
 	'page callback' => 'xassidareader_list_page',
 	'access callback' => TRUE,
 );

  return $items;
}

/**
 * **************************************************************************************
 * 
 * Implements hook_block_info()
 * 
 * @return Array
 * @author Papa Pathe SENE
 * 
 * **************************************************************************************
 */
function xassidareader_block_info() {

  $blocks = array();

  /**
   * Declare a block to list xassaides
   */
  $blocks['list_xassaides'] = array(
    'info' => t('Show a list of xassides'),
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;

}


/**
 * **************************************************************************************
 * 
 * Implements hook_block_view()
 *
 * @return Array
 * @author Papa Pathe SENE
 * 
 * **************************************************************************************
 * 
 */
function xassidareader_block_view($delta = '') {
  
  $block = array();

  switch ($delta) {

    /**
     * If liste_xassaides block is the one needed
     *
     * TODO 
     *   make the list of xassaides dynamic
     *   link each xassaide to its reading page 
     */
    case 'list_xassaides':

      /**
       * Create an array and populate it with xassaides
       */
      $xassaides = array();

      /**
       * Populate it with xassaides
       */      
      $xassaides[] = array (
        'data' => array (
          '#type'  => 'link',
          '#title' => 'mawaahibu naafih',
          '#href'  => 'xassidareader/'.'mawaahibu naafih'
        )
      );
      
      $xassaides[] = array (
        'data' => array (
          '#type'  => 'link',
          '#title' => 'jaawartou',
          '#href'  => 'xassidareader/'.'jaawartou'
        )
      );

      $block['subject'] = t('Listing Xassaides');
      $block['content']['xassaides_list'] = array (
        '#theme'      => 'item_list',          
        '#items'      => $xassaides, 
        '#pre_render' => array('_list_xassaides_block_prerender')
      );
      $block['content']['more_link'] = array(
        '#theme' => 'more_link',
        '#url'   => 'xassidareader',
        '#title' => t('view all')
      );
      break;

    default :
      break;
    
  }

  return $block;
}


/**
 * xassidareader_list_page
 * ------------------------------------------------------------------------
 * List all xassidas in the page
 *
 * @return Array
 * @author Papa Pathe SENE
 **/
function xassidareader_list_page()
{
	$content = array();


	$content['title'] = array(
		'#type'   => 'markup',
		'#markup' => '<h1>Listing Xassaides</h1>'
	);


	return $content;
}



/**
 * A pre_render function for the list_xassaides_block
 *
 * @return Array
 * @param  Array A list of xassaides
 * @author Papa Pathe SENE
 **/
function _list_xassaides_block_prerender($xassaides)
{

  foreach (array_keys($xassaides['#items']) AS $key) {
    if (is_array($xassaides['#items'][$key]['data'])) {
      $xassaides['#items'][$key]['data'] = drupal_render($xassaides['#items'][$key]['data']);
    }
  }
  return $xassaides;

}